POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "blog post 4",
    "author" : "Rishabh Sarkar",
    "url" : "http://localhost:3003/api/blogs",
    "likes" : 11,
    "user" : "6404ecf83ebcc248e34d20a6"
}

###
DELETE http://localhost:3003/api/blogs/6402e921137a77bde56735c9

###
PUT http://localhost:3003/api/blogs/6402f32f37ae38fbc161ddbd
Content-Type: application/json

{
    "title" : "third blog post updates",
    "author" : "Rishabh Sarkar 3",
    "url" : "http://localhost:3003/api/blogs/up",
    "likes" : 1
}

###
GET http://localhost:3003/api/blogs