POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content" : "VS code rest client is pretty handy tool",
    "important" : true
}

###
POST POST http://render-test-p5pq.onrender.com/api/notes
Content-Type: application/json

{
    "content" : "VS code rest client is pretty handy tool",
    "important" : true
}
