DELETE http://localhost:3001/api/persons/63fa25e0cdf14fe731d16656

###
GET http://localhost:3001/api/persons/63f6eb4c4386df9aac4e1edb

###
GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "rstest6",
    "number": "123-12-31211"
}